language: python
python:
  - '2.7'
  - '3.3'
install:
  - pip install -e .
  - pip install coverage coveralls
script:
  - coverage run --source=rembed setup.py test
  - coveralls
  - coverage report --fail-under=100
