language: python
python:
- '2.7'
- '3.3'
install:
- pip install -e .
- pip install coverage coveralls
script:
- coverage run setup.py test
- coveralls
- coverage report --fail-under=100
deploy:
  provider: pypi
  user:
    secure: pI+gRX1Bdo+BNjpWUzfZ9UanwHjLtfiXgdOqiA6lMZVwN3PTlcuHiJNcvTeJuQNYLs0+tVIWOMCIqRf6Jizo84q3QuopQZ4BPDUQeVpIUsRUnor9C63NAWA+XfxExB7J4b+nhF6KitN7igE91z8auQmqKqKaQhV1nQNpYPG9Ado=
  password:
    secure: mX+HgHuiCb94ZePN7SSiwOzB9OxIj/+sKID43S/CPbX4IJ0q78yEpaB9XfsIU3wSHsjqwytxYgelzfuhveLlpHfwS4sd3VLXZyNiLfxaqIz4USKoWSKsdhTrilxutXr8Yo8r17LODR74s27879LUsRw0ao0oExOFifYxT0h01iE=
  on:
    python: 2.7
    tags: true
    repo: matt-thomson/rembed-markdown
