language: python
python:
- '2.7'
- '3.3'
- '3.4'
install:
- pip install -e .
- pip install coverage coveralls wheel
script:
- coverage run setup.py test
- coveralls
- coverage report --fail-under=100
deploy:
  provider: pypi
  distributions: "sdist bdist_wheel"
  user:
    secure: R/mKfMxKp6sJ/jD9cD7A9+BHjQHwpEqRm72TR0zLDjJyUw82OKn9Fahi7z/virg6/kJzyD1R1kt3M9FgqEc2owE3lX8XSbIhv//Bic12NP7l93X0KjdOWdoyhDQRU95d8K55VKV0ff1SK2EgsZ/pL26bM+CZTj+1zrfLaUE20WI=
  password:
    secure: hQudXM3ALWvolUv95vx+SnnlfJi9SMxZVKY2Stt9azlHHYEvaJaMleyhzslfDG2gg+5Q958llbRF5umRgN7HmZnUUS7yWDNhhyu2525MpdDrxR+95Za3R3WGwpIwlkPgp9rujbFOwMlGHA7wHH2bs9kkrv8JMgs8DPBhJSvApuk=
  on:
    python: 2.7
    tags: true
    repo: pyembed/pyembed-markdown
    branch: master
