language: python
python:
- '2.7'
- '3.3'
install:
- pip install -e .
- pip install coverage coveralls
script:
- coverage run setup.py test
- coveralls
- coverage report --fail-under=100
deploy:
  provider: pypi
  user:
    secure: K4MvR2LZOtXYnuET/+wHq87PS6hWiYX3XmJgHpy6ZK0TWmmN8Q4rqFihvOMIzXE7gFodULMmaGDxS53LkMpmcduzGaqhopSc7yPwHglPv3qN8+lIGUl8WbksXuF9H6vfGixkDI0qqgfbryZLWc8PzvYd3ydIdVSZlXQTZ0nmAtk=
  password:
    secure: NoBtcBhHvgycd5QII9e8uYxJK7befN8FZfFbjUZWfA2dLseOyDxd1Zed55kKbtpMRjJDyi831YEn4ukoTnmSIkH0GfCvxHvnz8QQYioDRaWGQ/Wr7MupTVU8pO28CUmK7KygcQszcsJnVu9tAbs7FBONXUv2xz0oYgqPPNYZgZk=
  on:
    python: 2.7
    tags: true
    repo: rembed/rembed-markdown
